name: docker

on:
  workflow_call:
    inputs:
      version_value:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      version_value:
        required: false
        type: string

jobs:
  build_push:
    name: Build image and push
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository}}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.version_value }}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
