name: experimental

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Select a job to run"
        required: true
        type: choice
        options:
          - experimental_job1
          - cache

jobs:
  cache:
    if: ${{ github.event.inputs.job == 'cache' }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v2
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.arch }}-${{ runner.os }}-test
          path: |
            ~/.cache/deno
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
      - run: deno install --config ./scripts/deno.json
